export const CHARACTER_FETCH_SUCCESS = "CHARACTER_FETCH_SUCCESS";
export const CHARACTER_FETCH = "CHARACTER_FETCH";
export const CHARACTER_FETCH_FAILURE = "CHARACTER_FETCH_FAILURE";
export const CHARACTER_SELECT = "CHARACTER_SELECT";
